const { ESLint } = require("eslint");
const fs = require("fs");

async function main() {
  const eslint = new ESLint();
  const files = [
    "src/hooks/useLocation.ts",
    "src/hooks/useAuth.ts",
    "src/__tests__/stores.test.ts",
    "src/__tests__/MapScreen.test.tsx",
    "src/__tests__/MapScreenPerformance.test.tsx",
    "src/__tests__/NetworkStatusContext.test.tsx",
    "src/__tests__/OnboardingScreen.test.tsx",
    "src/__tests__/PendingProofsBanner.test.tsx",
    "src/__tests__/PublicKeyDisplay.test.tsx",
    "src/__tests__/TaskDetailScreen.test.tsx",
    "src/__tests__/authRefresh.test.ts",
    "src/__tests__/components.test.tsx",
    "src/__tests__/deepLinks.test.ts",
    "src/__tests__/earnings.test.ts",
    "src/__tests__/formatTokens.test.ts",
    "src/__tests__/geoUtils.test.ts",
    "src/__tests__/lobstr.test.ts",
    "src/__tests__/notifications.test.ts",
    "src/__tests__/prefsStore.test.ts",
    "src/__tests__/proofMetadata.test.ts",
    "src/__tests__/proofQueue.test.ts",
    "src/__tests__/quietHours.test.ts",
    "src/__tests__/signChallenge.test.ts",
    "src/__tests__/smoke.test.ts",
    "src/__tests__/sortTasks.test.ts",
    "src/__tests__/stellarPayment.test.ts",
    "src/__tests__/submitScreen.test.tsx",
    "src/__tests__/submitTabPress.test.ts",
    "src/__tests__/taskSelection.test.ts",
    "src/__tests__/useAuth.stats.test.ts",
    "src/__tests__/useLocation.test.tsx",
    "src/__tests__/useNetworkStatus.test.tsx",
    "src/__tests__/useProofStatus.test.tsx",
    "src/__tests__/useProofSubmit.ipfs.test.tsx",
    "src/__tests__/useProofSubmit.test.tsx",
    "src/__tests__/useTaskFeed.test.ts",
    "src/__tests__/useTaskFeedRefetch.test.tsx",
    "src/components/AchievementGrid.tsx",
    "src/components/ErrorBoundary.tsx",
    "src/components/LoadingSkeleton.tsx",
    "src/components/OfflineBanner.tsx",
    "src/components/PendingProofsBanner.tsx",
    "src/components/PublicKeyDisplay.tsx",
    "src/components/RewardBadge.tsx",
    "src/components/TaskCard.tsx",
    "src/components/TransactionHistory.tsx",
    "src/constants/notificationTypes.ts",
    "src/hooks/useNetworkStatus.ts",
    "src/hooks/useProofStatus.ts",
    "src/hooks/useProofSubmit.ts",
    "src/hooks/useStellarWallet.ts",
    "src/hooks/useTaskFeed.ts",
    "src/navigation/MainTabNavigator.tsx",
    "src/navigation/RootNavigator.tsx",
    "src/navigation/TaskStackNavigator.tsx",
    "src/navigation/deepLinks.ts",
    "src/navigation/submitTabPress.ts",
    "src/navigation/types.ts",
    "src/navigation/useAppNavigation.ts",
    "src/screens/EditProfileScreen.tsx",
    "src/screens/HomeScreen.tsx",
    "src/screens/MapScreen.tsx",
    "src/screens/NotificationPreferencesScreen.tsx",
    "src/screens/OnboardingScreen.tsx",
    "src/screens/ProfileScreen.tsx",
    "src/screens/SendTokensScreen.tsx",
    "src/screens/SubmitProofScreen.tsx",
    "src/screens/SubmitScreen.tsx",
    "src/screens/TaskDetailScreen.tsx",
    "src/screens/TaskListScreen.tsx",
    "src/screens/WalletScreen.tsx",
    "src/services/api.ts",
    "src/services/firebaseMessaging.ts",
    "src/services/ipfs.ts",
    "src/services/lobstr.ts",
    "src/services/notifications.ts",
    "src/services/proofQueue.ts",
    "src/services/stellar.ts",
    "src/store/activityStore.ts",
    "src/store/prefsStore.ts",
    "src/store/proofSyncStore.ts",
    "src/store/taskStore.ts",
    "src/store/userStore.ts",
    "src/store/walletStore.ts",
    "src/utils/achievements.ts",
    "src/utils/formatTokens.ts",
    "src/utils/geoUtils.ts",
    "src/utils/jwt.ts",
    "src/utils/proofMetadata.ts",
    "src/utils/quietHours.ts",
    "src/utils/sortTasks.ts",
    "src/utils/taskSelection.ts"
  ];
  
  const results = await eslint.lintFiles(files);
  const formatter = await eslint.loadFormatter("stylish");
  const resultText = formatter.format(results);
  
  fs.writeFileSync("lint_output.log", resultText);
  console.log("Done linting.");
}

main().catch(console.error);
